adapter:
  name: lincs.sigcom
  operation: get_json

params:
  path: signatures
  params:
    filter: '{"where":{"meta.pert_name":"fluoxetine"},"limit":1000,"skip":0}'
    contentRange: "true"

output:
  pretty: true
  path: assets/lincs_sigcom_fluoxetine_signatures.json
